### ISSUE TITLE
Able to register a user but unable to log in (401 Unauthorized)

### ISSUE THREAD

**Issue by ekauz** [clipable/clipable#163]
```
time=2023-06-19T02:39:02Z level=info msg=/api/auth/register method=OPTIONS read=0 B remoteAddr=127.0.0.1 status=200 took=0s written=0 B
time=2023-06-19T02:39:03Z level=info msg=/api/auth/login method=POST read=44 B remoteAddr=127.0.0.1 status=200 took=65ms written=0 B
time=2023-06-19T02:39:03Z level=info msg=/api/users/me method=GET read=0 B remoteAddr=127.0.0.1 status=401 took=0s written=0 B
time=2023-06-19T02:39:03Z level=info msg=/api/clips method=GET read=0 B remoteAddr=127.0.0.1 status=204 took=0s written=0 B
```

Running with docker-compose, looking at the postgres db the user gets created, but upon logging in it just redirects back to the main page without authenticating.  No error is displayed but the log indicates a 401.

**Comment by ImVexed** [comment]
Is the `COOKIE_DOMAIN` environment variable being set correctly? I would expect this if the cookie returned during register/login is not being sent on subsequent request because the domain the cookie was issued for is incorrect.

**Comment by ekauz** [comment]
From the docs I wasn't sure what I should be setting it to, but I tried leaving it on localhost, 'host.docker.internal', tried my machine's hostname, and 'local' since '.local' is how I route other machines on my network.  Am I using the wrong value there?

**Comment by ImVexed** [comment]
It should be whatever domain you're using to navigate to the website. The environment variable sets a field on the cookie when it's being issued by the server during a login that tells the browser what requests the cookie should be included on. So, if you set `COOKIE_DOMAIN` to `localhost` but then browse to the website on `clipable.local`, it will cause your browser to make requests like `clipable.local/api/auth/register` and your browser will never attempt to include the cookie, since it only wants to include it on requests to `localhost`.

**Comment by ekauz** [comment]
Ah, I see, I had only tried `<hostname>` or `<domain>` but what I needed was `<hostname>.<domain>` and it seems to be working now.  Not sure if this is a common problem but having an example like this in the docs might be useful.

Thanks for your help!

**Comment by ImVexed** [comment]
The wiki has been updated, and I've gone ahead and removed that environment variable from being a default that's provided. As in the absence of the field being present on a cookie, the browser will assume the current domain. Which is a sane default for 99% of use cases.

https://github.com/clipable/clipable/commit/608f33908a43bc4b31c93a7dc40084bfee71b711
